Repository elastic/ecs-dotnet, pull requests merged in 2020-06, with the labels that each got.

#81 add benchmarks for simple serialization cases
  .gitignore
  src/ecs-dotnet.sln
  tests/Elastic.CommonSchema.Benchmarks/Elastic.CommonSchema.Benchmarks.csproj
  tests/Elastic.CommonSchema.Benchmarks/Program.cs
  tests/Elastic.CommonSchema.Benchmarks/SerializingBase.cs
Labels: enhancement, v1.5.1

#78 NLog EcsLayout - Added support for Log Origin
  src/Elastic.CommonSchema.NLog/EcsLayout.cs
  src/Elastic.CommonSchema.Serilog/LogEventConverter.cs
  tests/Elastic.CommonSchema.NLog.Tests/Elastic.CommonSchema.NLog.Tests.csproj
  tests/Elastic.CommonSchema.NLog.Tests/LogTestsBase.cs
  tests/Elastic.CommonSchema.NLog.Tests/MessageTests.cs
Labels: enhancement, v1.5.1

#83 fix #79 only inject layout renderer keys for APM if Elastic.Apm.NLog …
  src/Elastic.CommonSchema.NLog/EcsLayout.cs
Labels: bug, v1.5.1

#82 Expose Serialize(StringBuilder) overload
  src/Elastic.CommonSchema.NLog/EcsLayout.cs
  src/Elastic.CommonSchema/Base.Serialization.cs
  src/Elastic.CommonSchema/Elastic.CommonSchema.csproj
  src/Elastic.CommonSchema/Serialization/EcsSerializerFactory.cs
  src/Elastic.CommonSchema/Serialization/ReusableUtf8JsonWriter.cs
  tests/Elastic.CommonSchema.Benchmarks/Elastic.CommonSchema.Benchmarks.csproj
  tests/Elastic.CommonSchema.Benchmarks/SerializingStringBuilderBase.cs
  tests/Elastic.CommonSchema.NLog.Tests/OutputTests.cs
Labels: enhancement, v1.5.1

#80 Update build
  .ci/Jenkinsfile
  .ci/docker/sdk-linux/Dockerfile
  .github/workflows/ci.yml
  Directory.Build.props
  build/nuget-icon-aux.png
  build/nuget-icon.png
  build/scripts/Building.fs
  build/scripts/CommandLine.fs
  build/scripts/Commandline.fs
  build/scripts/Paths.fs
  build/scripts/Program.fs
  build/scripts/ReleaseNotes.fs
  build/scripts/Releasing.fs
  build/scripts/Targets.fs
  build/scripts/Testing.fs
  build/scripts/Tooling.fs
  build/scripts/Versioning.fs
  build/scripts/scripts.fsproj
  dotnet-tools.json
  ecs-dotnet.sln
  ecs-dotnet.sln.DotSettings
  examples/aspnetcore-with-serilog/AspnetCoreExample.csproj
  examples/aspnetcore-with-serilog/Controllers/WeatherForecastController.cs
  examples/aspnetcore-with-serilog/Startup.cs
  global.json
  nuget-icon.png
  src/Directory.Build.props
  src/Elastic.Apm.NLog/Elastic.Apm.NLog.csproj
  src/Elastic.Apm.SerilogEnricher/Elastic.Apm.SerilogEnricher.csproj
  src/Elastic.CommonSchema.BenchmarkDotNetExporter/Elastic.CommonSchema.BenchmarkDotNetExporter.csproj
  src/Elastic.CommonSchema.NLog/Elastic.CommonSchema.NLog.csproj
  src/Elastic.CommonSchema.Serilog/Elastic.CommonSchema.Serilog.csproj
  src/Elastic.CommonSchema.Serilog/Lib/UAParser.cs
  src/Elastic.CommonSchema/Elastic.CommonSchema.csproj
  src/Elastic.CommonSchemaNEST/Elastic.CommonSchemaNEST.csproj
  src/Generator/Generator.csproj
  src/Library.build.props
  src/PublishArtifacts.build.props
  src/Specification/Specification.csproj
  tests/Directory.Build.props
  tests/Elastic.Apm.SerilogEnricher.Test/Elastic.Apm.SerilogEnricher.Test.csproj
  tests/Elastic.Apm.Test.Common/Elastic.Apm.Test.Common.csproj
  tests/Elastic.CommonSchema.BenchmarkDotNetExporter.IntegrationTests/BdNetExporterTests.cs
  tests/Elastic.CommonSchema.BenchmarkDotNetExporter.IntegrationTests/BenchmarkCluster.cs
  tests/Elastic.CommonSchema.BenchmarkDotNetExporter.IntegrationTests/Md5VsSha256.cs
  tests/Elastic.CommonSchema.Benchmarks/Elastic.CommonSchema.Benchmarks.csproj
  tests/Elastic.CommonSchema.NLog.Tests/Elastic.CommonSchema.NLog.Tests.csproj
Labels: enhancement

#88 ci: enable CI release automation
  .ci/Jenkinsfile
  .ci/deploy.sh
  .ci/docker/sdk-linux/Dockerfile
  .ci/jobs/defaults.yml
  build/scripts/Targets.fs
Labels: automation

#89 [CI] deploy to nuget enabled
  .ci/Jenkinsfile
  .github/workflows/ci.yml
Labels: automation

#93 [ci] fix dotnet nuget push duplicated and filter
  .ci/deploy.bat
  .ci/deploy.sh
Labels: automation
