Repository elastic/ecs-dotnet, pull requests merged in 2020-03, with the labels that each got.

#57 ci(jenkins): enable JUnit output
  .ci/Jenkinsfile
  build/scripts/Testing.fs
  tests/Elastic.Apm.NLog.Test/Elastic.Apm.NLog.Test.csproj
  tests/Elastic.Apm.SerilogEnricher.Test/Elastic.Apm.SerilogEnricher.Test.csproj
  tests/Elastic.Apm.Test.Common/Elastic.Apm.Test.Common.csproj
  tests/Elastic.CommonSchema.BenchmarkDotNetExporter.IntegrationTests/Elastic.CommonSchema.BenchmarkDotNetExporter.IntegrationTests.csproj
  tests/Elastic.CommonSchema.NLog.Tests/Elastic.CommonSchema.NLog.Tests.csproj
  tests/Elastic.CommonSchema.Serilog.Tests/Elastic.CommonSchema.Serilog.Tests.csproj
  tests/Elastic.CommonSchema.Tests/Elastic.CommonSchema.Tests.csproj
Labels: automation

#53 ci(jenkins): deploy to AppVeyor when master branch
  .ci/Jenkinsfile
  .ci/deploy.bat
  README.md
  appveyor.yml
Labels: automation

#63 Example to demonstrate registration of the EcsTextFormatter within an AspnetCore application.
  README.md
  examples/aspnetcore-with-serilog/AspnetCoreExample.csproj
  examples/aspnetcore-with-serilog/Controllers/WeatherForecastController.cs
  examples/aspnetcore-with-serilog/Program.cs
  examples/aspnetcore-with-serilog/README.md
  examples/aspnetcore-with-serilog/Startup.cs
  examples/aspnetcore-with-serilog/WeatherForecast.cs
  examples/aspnetcore-with-serilog/appsettings.Development.json
  examples/aspnetcore-with-serilog/appsettings.json
  src/Elastic.CommonSchema.Serilog/Elastic.CommonSchema.Serilog.csproj
  src/Elastic.CommonSchema.Serilog/Http/HttpContextAccessorAdapter.cs
  src/Elastic.CommonSchema.Serilog/Http/HttpContextAdapter.cs
  src/Elastic.CommonSchema.Serilog/Lib/UAParser.cs
  src/Elastic.CommonSchema.Serilog/Lib/UAParser.regexes.yaml
  src/ecs-dotnet.sln
Labels: bug, enhancement, v1.4.3

#60 Implement ECS schema 1.5
  src/Elastic.CommonSchema.Serilog/Http/HttpContextAccessorAdapter.cs
  src/Elastic.CommonSchema.Serilog/LogEventConverter.cs
  src/Elastic.CommonSchema/Base.Serialization.cs
  src/Elastic.CommonSchema/Serialization/BaseJsonConverter.cs
  src/Elastic.CommonSchema/Serialization/BaseJsonFormatter.Generated.cs
  src/Elastic.CommonSchema/Serialization/EcsJsonConverterBase.cs
  src/Elastic.CommonSchema/Serialization/LogJsonConverter.cs
  src/Elastic.CommonSchema/Types.Generated.cs
  src/Elastic.CommonSchemaNEST/TypeMappings.Generated.cs
  src/Generator/CodeConfiguration.cs
  src/Generator/ExtensionMethods.cs
  src/Generator/FileGenerator.cs
  src/Generator/NLogHelper.cs
  src/Generator/Program.cs
  src/Generator/Schema/EcsSpecification.cs
  src/Generator/Schema/Field.cs
  src/Generator/Schema/FieldAllowedValue.cs
  src/Generator/Schema/FieldLevel.cs
  src/Generator/Schema/FieldMultiField.cs
  src/Generator/Schema/FieldType.cs
  src/Generator/Schema/NestedFields.cs
  src/Generator/Schema/YamlSchema.cs
  src/Generator/Schema/YamlSchemaReusable.cs
  src/Generator/Schema/YamlSpecification.cs
  src/Generator/SchemaExtensionMethods.cs
  src/Generator/SpecificationDownloader.cs
  src/Generator/Views/BaseJsonFormatter.Generated.cshtml
  src/Generator/Views/TypeMappings.Generated.cshtml
  src/Generator/Views/Types.Generated.cshtml
  src/Specification/1.5/Core/ecs_flat.yml
  src/Specification/1.5/Core/ecs_nested.yml
  src/Specification/1.5/Core/root.html
  src/Specification/1.5/Template6/root.html
  src/Specification/1.5/Template6/template.json
  src/Specification/1.5/Template7/root.html
  src/Specification/1.5/Template7/template.json
  src/ecs-dotnet.sln
  tests/Elastic.CommonSchema.Tests/Serializes.cs
Labels: v1.5.0
