Repository elastic/ecs-dotnet, pull requests merged in 2020-07, with the labels that each got.

#85 Stand alone logger provider for Microsoft.Extensions.Logging that uses ECS to log directly to Elasticsearch
  ecs-dotnet.sln
  src/Elasticsearch.Extensions.Logging/ConnectionPoolType.cs
  src/Elasticsearch.Extensions.Logging/Elasticsearch.Extensions.Logging.csproj
  src/Elasticsearch.Extensions.Logging/ElasticsearchDataProcessor.cs
  src/Elasticsearch.Extensions.Logging/ElasticsearchLogger.cs
  src/Elasticsearch.Extensions.Logging/ElasticsearchLoggerOptions.cs
  src/Elasticsearch.Extensions.Logging/ElasticsearchLoggerOptionsSetup.cs
  src/Elasticsearch.Extensions.Logging/ElasticsearchLoggerProvider.cs
  src/Elasticsearch.Extensions.Logging/LogEvent.cs
  src/Elasticsearch.Extensions.Logging/LoggingBuilderExtensions.cs
  src/Elasticsearch.Extensions.Logging/ReadMe.md
Labels: enhancement, v1.6.0

#94 NLog EcsLayout - Add support for ExcludeProperties
  src/Elastic.CommonSchema.NLog/EcsLayout.cs
  tests/Elastic.CommonSchema.NLog.Tests/LogTestsBase.cs
  tests/Elastic.CommonSchema.NLog.Tests/MessageTests.cs
Labels: enhancement, v1.5.3, v1.6.0

#98 Added ElasticCloud logging
  src/Elasticsearch.Extensions.Logging/ElasticsearchDataProcessor.cs
  src/Elasticsearch.Extensions.Logging/ElasticsearchLoggerOptions.cs
  src/Elasticsearch.Extensions.Logging/LoggingBuilderExtensions.cs
  src/Elasticsearch.Extensions.Logging/ShipTo.cs
Labels: enhancement, v1.5.3, v1.6.0

#90 Feature/serilog property filter
  src/Elastic.CommonSchema.Serilog/EcsTextFormatterConfiguration.cs
  src/Elastic.CommonSchema.Serilog/LogEventConverter.cs
  tests/Elastic.CommonSchema.Serilog.Tests/LogEventPropFilterTests.cs
  tests/Elastic.CommonSchema.Serilog.Tests/LogTestsBase.cs
Labels: enhancement, v1.5.3
