Repository elastic/ecs-dotnet, pull requests merged in 2022-09, with the labels that each got.

#211 Fix Metadata serialization
  src/Elastic.CommonSchema.Generator/Views/EcsDocument.Generated.cshtml
  src/Elastic.CommonSchema.Generator/Views/EcsDocumentJsonConverter.Generated.cshtml
  src/Elastic.CommonSchema.NLog/EcsLayout.cs
  src/Elastic.CommonSchema.Serilog/LogEventConverter.cs
  src/Elastic.CommonSchema/EcsDocument.Generated.cs
  src/Elastic.CommonSchema/EcsDocumentJsonConverter.Generated.cs
  src/Elastic.CommonSchema/MetadataDictionary.cs
  src/Elastic.CommonSchema/Serialization/DictionaryJsonConverterFactory.cs
  src/Elastic.CommonSchema/Serialization/EcsJsonConverterBase.cs
  src/Elastic.CommonSchema/Serialization/JsonConfiguration.cs
  src/Elastic.CommonSchema/Serialization/MetaDataDictionaryConverter.cs
  src/Elastic.CommonSchema/Serialization/MetadataDictionaryConverter.cs
  tests/Elastic.CommonSchema.NLog.Tests/MessageTests.cs
  tests/Elastic.CommonSchema.Serilog.Tests/MessageTests.cs
  tests/Elastic.CommonSchema.Tests/Repro/GithubIssue29.cs
  tests/Elastic.CommonSchema.Tests/Serializes.cs
Labels: bug, breaking, v8.4.0

#195 NLog EcsLayout with support for Http and Url properties
  src/Elastic.CommonSchema.NLog/EcsLayout.cs
  src/Elastic.CommonSchema.NLog/README.md
Labels: enhancement, v8.4.0

#204 Serilog: refactor url and server population
  examples/aspnetcore-with-serilog/README.md
  src/Elastic.CommonSchema.Serilog/Elastic.CommonSchema.Serilog.csproj
  src/Elastic.CommonSchema.Serilog/Http/HttpContextAccessorAdapter.cs
Labels: enhancement, v8.4.0

#218 Ensure ECS version is the schema version
  src/Elastic.CommonSchema.Generator/Projection/TypeProjector.cs
  src/Elastic.CommonSchema.Generator/Views/EcsDocument.Generated.cshtml
  src/Elastic.CommonSchema/EcsDocument.Generated.cs
  tests/Elasticsearch.Extensions.Logging.IntegrationTests/LoggingToDataStreamTests.cs
Labels: bug, v8.4.0
