Repository elastic/ecs-dotnet, pull requests merged in 2023-01, with the labels that each got.

#228 docs: remove log4net
  docs/setup.asciidoc
  docs/tab-widgets/code.asciidoc
  docs/tab-widgets/ecs-integration-widget.asciidoc
  docs/tab-widgets/ecs-integration.asciidoc
Labels: Team:Docs

#229 Set ECS fields from message templates
  src/Elastic.CommonSchema.Generator/Elastic.CommonSchema.Generator.csproj
  src/Elastic.CommonSchema.Generator/FileGenerator.cs
  src/Elastic.CommonSchema.Generator/Projection/ProjectionTypeExtensions.cs
  src/Elastic.CommonSchema.Generator/Projection/PropertyReference.cs
  src/Elastic.CommonSchema.Generator/Projection/Types.cs
  src/Elastic.CommonSchema.Generator/Views/EcsDocument.Generated.cshtml
  src/Elastic.CommonSchema.Generator/Views/LogTemplateProperties.Generated.cshtml
  src/Elastic.CommonSchema.Generator/Views/PropDispatch.Generated.cshtml
  src/Elastic.CommonSchema.Log4net/LoggingEventConverter.cs
  src/Elastic.CommonSchema.Log4net/README.md
  src/Elastic.CommonSchema.NLog/EcsLayout.cs
  src/Elastic.CommonSchema.NLog/README.md
  src/Elastic.CommonSchema.Serilog/LogEventConverter.cs
  src/Elastic.CommonSchema.Serilog/README.md
  src/Elastic.CommonSchema/EcsDocument.Generated.cs
  src/Elastic.CommonSchema/EcsJsonContext.Generated.cs
  src/Elastic.CommonSchema/FieldSets.Generated.cs
  src/Elastic.CommonSchema/LogTemplateProperties.Generated.cs
  src/Elastic.CommonSchema/MetadataDictionary.cs
  src/Elastic.CommonSchema/PropDispatch.Generated.cs
  src/Elastic.CommonSchema/PropDispatch.cs
  tests/Elastic.CommonSchema.Log4net.Tests/EcsFieldsAsPropertiesTests.cs
  tests/Elastic.CommonSchema.Log4net.Tests/LogTestsBase.cs
  tests/Elastic.CommonSchema.Log4net.Tests/MessageTests.cs
  tests/Elastic.CommonSchema.Log4net.Tests/TestAppender.cs
  tests/Elastic.CommonSchema.NLog.Tests/ApmTests.cs
  tests/Elastic.CommonSchema.NLog.Tests/EcsFieldsInTemplateTests.cs
  tests/Elastic.CommonSchema.NLog.Tests/MessageTests.cs
  tests/Elastic.CommonSchema.Serilog.Tests/EcsFieldsInTemplateTests.cs
  tests/Elastic.CommonSchema.Serilog.Tests/LogEventPropFilterTests.cs
  tests/Elastic.CommonSchema.Serilog.Tests/MessageTests.cs
  tests/Elastic.CommonSchema.Tests/Specs/Spec.cs
  tests/Elastic.Ingest.IntegrationTests/CommonSchemaIngestionTests.cs
Labels: enhancement, breaking, v8.4.0

#230 Fix #224 cache process lookup in serilog formatter.
  src/Elastic.CommonSchema.Serilog/LogEventConverter.cs
Labels: bug, v8.4.0

#221 EcsJsonConfiguration - With converters to protect against bad types
  src/Elastic.CommonSchema/Serialization/JsonConfiguration.cs
  src/Elastic.CommonSchema/Serialization/MetadataDictionaryConverter.cs
  tests/Elastic.CommonSchema.NLog.Tests/ApmTests.cs
  tests/Elastic.CommonSchema.NLog.Tests/EcsFieldsInTemplateTests.cs
  tests/Elastic.CommonSchema.NLog.Tests/LogTestsBase.cs
  tests/Elastic.CommonSchema.NLog.Tests/MessageTests.cs
  tests/Elastic.CommonSchema.NLog.Tests/OutputTests.cs
Labels: bug, v8.4.0

#231 Fixes #86 only write log level once
  src/Elastic.CommonSchema.Generator/CodeConfiguration.cs
  src/Elastic.CommonSchema.Generator/FileGenerator.cs
  src/Elastic.CommonSchema.Generator/Projection/ProjectionTypeExtensions.cs
  src/Elastic.CommonSchema.Generator/Projection/PropertyReference.cs
  src/Elastic.CommonSchema.Generator/Projection/TypeProjector.cs
  src/Elastic.CommonSchema.Generator/Views/EcsDocumentJsonConverter.Generated.cshtml
  src/Elastic.CommonSchema.Generator/Views/EcsJsonContext.Generated.cshtml
  src/Elastic.CommonSchema.Generator/Views/EcsLogJsonConverter.Generated.cshtml
  src/Elastic.CommonSchema/Entities.cs
  src/Elastic.CommonSchema/Serialization/EcsDocumentJsonConverter.Generated.cs
  src/Elastic.CommonSchema/Serialization/EcsDocumentJsonConverter.cs
  src/Elastic.CommonSchema/Serialization/EcsJsonContext.Generated.cs
  src/Elastic.CommonSchema/Serialization/EcsJsonConverterBase.cs
  src/Elastic.CommonSchema/Serialization/EcsLogJsonConverter.Generated.cs
  src/Elastic.CommonSchema/Serialization/EcsLogJsonConverter.cs
  src/Elastic.CommonSchema/Serialization/JsonConfiguration.cs
  tests/Elastic.CommonSchema.Tests/LogLevelTests.cs
Labels: bug, v8.4.0

#232 Ensure ecs.version is always written
  src/Elastic.CommonSchema.Generator/Elastic.CommonSchema.Generator.csproj
  src/Elastic.CommonSchema.Generator/FileGenerator.cs
  src/Elastic.CommonSchema.Generator/Projection/TypeProjector.cs
  src/Elastic.CommonSchema.Generator/Projection/Types.cs
  src/Elastic.CommonSchema.Generator/Views/EcsDocumentJsonConverter.Generated.cshtml
  src/Elastic.CommonSchema.Generator/Views/EcsLogJsonConverter.Generated.cshtml
  src/Elastic.CommonSchema.Generator/Views/EcsShouldSerializeJsonConverter.Generated.cshtml
  src/Elastic.CommonSchema.Generator/Views/Entities.ShouldSerialize.Generated.cshtml
  src/Elastic.CommonSchema/Entities.Generated.cs
  src/Elastic.CommonSchema/Entities.ShouldSerialize.Generated.cs
  src/Elastic.CommonSchema/Entities.cs
  src/Elastic.CommonSchema/Serialization/EcsDocumentJsonConverter.Generated.cs
  src/Elastic.CommonSchema/Serialization/EcsDocumentJsonConverter.cs
  src/Elastic.CommonSchema/Serialization/EcsLogJsonConverter.Generated.cs
  src/Elastic.CommonSchema/Serialization/EcsShouldSerializeJsonConverter.Generated.cs
  src/Elastic.CommonSchema/Serialization/EcsShouldSerializeJsonConverter.cs
  src/Elastic.CommonSchema/Serialization/JsonConfiguration.cs
  tests/Elastic.CommonSchema.Tests/EcsVersionTests.cs
  tests/Elastic.CommonSchema.Tests/LogLevelTests.cs
  tests/Elastic.CommonSchema.Tests/Specs/spec.json
Labels: enhancement, v8.4.0

#235 synchronize ecs-logging spec
  tests/Elastic.CommonSchema.Tests/Specs/spec.json
Labels: automation, v8.4.0

#237 remove elastic/elastic-ingest-dotnet projects and reference them as nuget packages
  ecs-dotnet.sln
  examples/Elastic.Ingest.Apm.Example/Elastic.Ingest.Apm.Example.csproj
  examples/Elastic.Ingest.Apm.Example/Program.cs
  examples/Elastic.Ingest.OpenTelemetry.Example/Elastic.Ingest.OpenTelemetry.Example.csproj
  examples/Elastic.Ingest.OpenTelemetry.Example/Program.cs
  examples/Elasticsearch.Extensions.Logging.Example/Program.cs
  src/Elastic.CommonSchema.BenchmarkDotNetExporter/ElasticsearchBenchmarkExporter.cs
  src/Elastic.Ingest.Apm/ApmChannel.cs
  src/Elastic.Ingest.Apm/ApmChannelOptions.cs
  src/Elastic.Ingest.Apm/Elastic.Ingest.Apm.csproj
  src/Elastic.Ingest.Apm/Helpers/Time.cs
  src/Elastic.Ingest.Apm/Model/IngestResponse.cs
  src/Elastic.Ingest.Apm/Model/Transaction.cs
  src/Elastic.Ingest.Elasticsearch.CommonSchema/CommonSchemaChannel.cs
  src/Elastic.Ingest.Elasticsearch.CommonSchema/Elastic.Ingest.Elasticsearch.CommonSchema.csproj
  src/Elastic.Ingest.Elasticsearch/DataStreams/DataStreamChannel.cs
  src/Elastic.Ingest.Elasticsearch/DataStreams/DataStreamChannelOptions.cs
  src/Elastic.Ingest.Elasticsearch/DataStreams/DataStreamName.cs
  src/Elastic.Ingest.Elasticsearch/Elastic.Ingest.Elasticsearch.csproj
  src/Elastic.Ingest.Elasticsearch/ElasticsearchBufferOptions.cs
  src/Elastic.Ingest.Elasticsearch/ElasticsearchChannelBase.cs
  src/Elastic.Ingest.Elasticsearch/ElasticsearchChannelOptionsBase.cs
  src/Elastic.Ingest.Elasticsearch/ElasticsearchChannelStatics.cs
  src/Elastic.Ingest.Elasticsearch/Indices/IndexChannel.cs
  src/Elastic.Ingest.Elasticsearch/Indices/IndexChannelOptions.cs
  src/Elastic.Ingest.Elasticsearch/IsExternalInit.cs
  src/Elastic.Ingest.Elasticsearch/Serialization/BulkOperationHeader.cs
  src/Elastic.Ingest.Elasticsearch/Serialization/BulkResponse.cs
  src/Elastic.Ingest.Elasticsearch/Serialization/BulkResponseItem.cs
  src/Elastic.Ingest.OpenTelemetry/CustomActivityExporter.cs
  src/Elastic.Ingest.OpenTelemetry/CustomOtlpTraceExporter.cs
  src/Elastic.Ingest.OpenTelemetry/Elastic.Ingest.OpenTelemetry.csproj
  src/Elastic.Ingest.Transport/Elastic.Ingest.Transport.csproj
  src/Elastic.Ingest.Transport/TransportChannelBase.cs
  src/Elastic.Ingest.Transport/TransportChannelOptionsBase.cs
  src/Elastic.Ingest/BufferOptions.cs
  src/Elastic.Ingest/ChannelBase.cs
  src/Elastic.Ingest/ChannelBuffer.cs
  src/Elastic.Ingest/ChannelOptionsBase.cs
  src/Elastic.Ingest/Elastic.Ingest.csproj
  src/Elasticsearch.Extensions.Logging/Elasticsearch.Extensions.Logging.csproj
  src/Elasticsearch.Extensions.Logging/ElasticsearchLogger.cs
  src/Elasticsearch.Extensions.Logging/ElasticsearchLoggerProvider.cs
  tests/Elastic.CommonSchema.Serilog.Sink.IntegrationTests/SerilogOutputTests.cs
  tests/Elastic.Ingest.IntegrationTests/CommonSchemaIngestionTests.cs
  tests/Elastic.Ingest.IntegrationTests/Elastic.Ingest.IntegrationTests.csproj
  tests/Elastic.Ingest.IntegrationTests/IngestionCluster.cs
  tests/Elastic.Ingest.Tests/BehaviorTests.cs
  tests/Elastic.Ingest.Tests/Elastic.Ingest.Tests.csproj
  tests/Elastic.Ingest.Tests/Elasticsearch/BulkResponseBuilder.cs
  tests/Elastic.Ingest.Tests/Elasticsearch/ElasticsearchChannelTests.cs
  tests/Elastic.Ingest.Tests/Elasticsearch/SerializationTests.cs
  tests/Elastic.Ingest.Tests/Elasticsearch/Setup.cs
Labels: dependencies, v8.4.0

#236 use GitHub actions (linux support)
  .ci/Jenkinsfile
  .github/workflows/opentelemetry.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test-reporter.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: automation, Team:Automation

#241 move over to Elastic.Ingest.* nuget packages
  ecs-dotnet.sln
  examples/Elasticsearch.Extensions.Logging.Example/Program.cs
  src/Elastic.CommonSchema.BenchmarkDotNetExporter/ElasticsearchBenchmarkExporter.cs
  src/Elastic.CommonSchema.BenchmarkDotNetExporter/ElasticsearchBenchmarkExporterOptions.cs
  src/Elastic.CommonSchema.Generator/Projection/IndexTemplate.cs
  src/Elastic.CommonSchema.Generator/Views/IndexTemplates.Generated.cshtml
  src/Elastic.CommonSchema.Serilog.Sink/ElasticsearchSink.cs
  src/Elastic.CommonSchema/IndexTemplates.Generated.cs
  src/Elastic.CommonSchema/Serialization/EcsShouldSerializeJsonConverter.Generated.cs
  src/Elastic.Ingest.Elasticsearch.CommonSchema/CommonSchemaChannel.cs
  src/Elastic.Ingest.Elasticsearch.CommonSchema/EcsDataStreamChannel.cs
  src/Elastic.Ingest.Elasticsearch.CommonSchema/EcsIndexChannel.cs
  src/Elastic.Ingest.Elasticsearch.CommonSchema/Elastic.Ingest.Elasticsearch.CommonSchema.csproj
  src/Elasticsearch.Extensions.Logging/ElasticsearchLoggerProvider.cs
  src/Elasticsearch.Extensions.Logging/Options/DataStreamNameOptions.cs
  src/Elasticsearch.Extensions.Logging/Options/ElasticsearchLoggerOptions.cs
  tests/Elastic.CommonSchema.BenchmarkDotNetExporter.IntegrationTests/BdNetExporterTests.cs
  tests/Elastic.Ingest.Elasticsearch.CommonSchema.IntegrationTests/DataStreamIngestionTests.cs
  tests/Elastic.Ingest.Elasticsearch.CommonSchema.IntegrationTests/Elastic.Ingest.Elasticsearch.CommonSchema.IntegrationTests.csproj
  tests/Elastic.Ingest.Elasticsearch.CommonSchema.IntegrationTests/IndexIngestionTests.cs
  tests/Elastic.Ingest.Elasticsearch.CommonSchema.IntegrationTests/IngestionCluster.cs
  tests/Elastic.Ingest.Elasticsearch.CommonSchema.IntegrationTests/IntegrationTestBase.cs
  tests/Elastic.Ingest.Elasticsearch.CommonSchema.IntegrationTests/TestDocument.cs
Labels: enhancement, v8.4.0

#238 action: release
  .ci/Jenkinsfile
  .github/workflows/docker-run/action.yml
  .github/workflows/release-main.yml
  .github/workflows/release.yml
Labels: automation, Team:Automation
